//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconStudio.Meet.EjpLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiliconStudio.Meet.EjpLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open Assignment. File Not Found..
        /// </summary>
        internal static string EX_Fnf_OpenFailed {
            get {
                return ResourceManager.GetString("EX_Fnf_OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xps Document could not be loaded/opened. File or Part not found..
        /// </summary>
        internal static string EX_Fnf_XPSNotFound {
            get {
                return ResourceManager.GetString("EX_Fnf_XPSNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 2 knowledgemaps are allowed..
        /// </summary>
        internal static string EX_KMCount {
            get {
                return ResourceManager.GetString("EX_KMCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open Assignment. Assignment Meta Data not found..
        /// </summary>
        internal static string EX_MDnf_OpenFailed {
            get {
                return ResourceManager.GetString("EX_MDnf_OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open Assignment. All the necessary parts could not be read..
        /// </summary>
        internal static string Ex_Pack_OpenFailed {
            get {
                return ResourceManager.GetString("Ex_Pack_OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not construct all necessary parts of the Assignment Package..
        /// </summary>
        internal static string EX_Pack_SaveFailed {
            get {
                return ResourceManager.GetString("EX_Pack_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 2 reports are allowed..
        /// </summary>
        internal static string EX_ReportCount {
            get {
                return ResourceManager.GetString("EX_ReportCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the file in the given location. Make sure you are not trying to overwrite an assignment that is already open in another instance of E Journal Plus..
        /// </summary>
        internal static string EX_SaveFailed {
            get {
                return ResourceManager.GetString("EX_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have file persmissions sufficient to fully qualify the path to the given XPS Document. Move the file to another location and try opening it again..
        /// </summary>
        internal static string EX_Sec_OpenFileFailed {
            get {
                return ResourceManager.GetString("EX_Sec_OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称未設定.
        /// </summary>
        internal static string Str_UnnamedStudyTitle {
            get {
                return ResourceManager.GetString("Str_UnnamedStudyTitle", resourceCulture);
            }
        }
    }
}
