//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconStudio.Meet.EjpControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiliconStudio.Meet.EjpControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このナレジマップは今ロックされていますので、新しい項目を追加出来ません。.
        /// </summary>
        internal static string ERR_AddKMEntityFailed_Locked {
            get {
                return ResourceManager.GetString("ERR_AddKMEntityFailed_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このリポートは、現在編集出来ません.
        /// </summary>
        internal static string ERR_ReportEditFailed_Locked {
            get {
                return ResourceManager.GetString("ERR_ReportEditFailed_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正しいUrlを入力して下さい。必ず「http://」から入力して下さい。.
        /// </summary>
        internal static string ERR_UrlWinAddFailed_Format {
            get {
                return ResourceManager.GetString("ERR_UrlWinAddFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 説明を入力して下さい!.
        /// </summary>
        internal static string ERR_UrlWinAddFailed_NoExpl {
            get {
                return ResourceManager.GetString("ERR_UrlWinAddFailed_NoExpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ガイドを削除することが出来ませんでした。.
        /// </summary>
        internal static string EX_DelGuideFailed {
            get {
                return ResourceManager.GetString("EX_DelGuideFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Image source stream is not accessable. The source is not a BitmapImage/Uri..
        /// </summary>
        internal static string EX_LoadGuideFailed {
            get {
                return ResourceManager.GetString("EX_LoadGuideFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image entity source stream is not accessable. The source is not a BitmapImage/Uri..
        /// </summary>
        internal static string EX_LoadKMIMGEntityFailed {
            get {
                return ResourceManager.GetString("EX_LoadKMIMGEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リンクを作成する際に失敗しました。\nUrlを正しく入力したかどうかを確かめた上もう一度試してみてください。.
        /// </summary>
        internal static string EX_ReportAddUrlFailed {
            get {
                return ResourceManager.GetString("EX_ReportAddUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レポートを書き出すする際に失敗しました。.
        /// </summary>
        internal static string EX_ReportExportFailed {
            get {
                return ResourceManager.GetString("EX_ReportExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load a Report in the current Assignment. Perhaps the Assignment was created with an earlier version of eJournalPlus?.
        /// </summary>
        internal static string EX_ReportLoadFailed_Version {
            get {
                return ResourceManager.GetString("EX_ReportLoadFailed_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷する際に失敗しました。.
        /// </summary>
        internal static string EX_ReportPrintFailed {
            get {
                return ResourceManager.GetString("EX_ReportPrintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この位置に引用出来ませんでした。もう一度他の位置で試して見て下さい。なお，引用部分の上に新しい引用を重ねることはできません．ずらして引用してください。.
        /// </summary>
        internal static string EX_ReportReferenceAddFailed {
            get {
                return ResourceManager.GetString("EX_ReportReferenceAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択された画像をガイドにすることが出来ませんでした。.
        /// </summary>
        internal static string EX_SetGuideFailed {
            get {
                return ResourceManager.GetString("EX_SetGuideFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このプッシュピンコメントをすべて消しますが宜しいですか？.
        /// </summary>
        internal static string Q_DelPushPinComment {
            get {
                return ResourceManager.GetString("Q_DelPushPinComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いま、あなたが消そうとしている線は、ナレッジマップ上にある１つ以上のオブジェクトと関連しています。この線を消すと、関連するすべてのオブジェクトがナレッジマップからも削除されます。この動作は取り消せません。それでもこの線を消しますか？.
        /// </summary>
        internal static string Q_DocVDelConnectedLine {
            get {
                return ResourceManager.GetString("Q_DocVDelConnectedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元に戻せば線が消えます。その線は、ナレッジマップ上にある１つ以上のオブジェクトと関連しています。この線を消すと、関連するすべてのオブジェクトがナレッジマップからも削除されます。それでもこの線を消しますか？.
        /// </summary>
        internal static string Q_DocVUndoConnectedLine {
            get {
                return ResourceManager.GetString("Q_DocVUndoConnectedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Str_ConvertedCommentNodeTitle {
            get {
                return ResourceManager.GetString("Str_ConvertedCommentNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string Str_ErrorDlgTitle {
            get {
                return ResourceManager.GetString("Str_ErrorDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナレッジマップがロックされている。.
        /// </summary>
        internal static string Str_MsgTitle_KMLocked {
            get {
                return ResourceManager.GetString("Str_MsgTitle_KMLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レポートがロックされている。.
        /// </summary>
        internal static string Str_MsgTitle_ReportLocked {
            get {
                return ResourceManager.GetString("Str_MsgTitle_ReportLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称未設定.
        /// </summary>
        internal static string Str_NewKMIMGEntityTitle {
            get {
                return ResourceManager.GetString("Str_NewKMIMGEntityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力して下さい。.
        /// </summary>
        internal static string Str_NewKMLabelDefaultContent {
            get {
                return ResourceManager.GetString("Str_NewKMLabelDefaultContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Title.
        /// </summary>
        internal static string Str_NewKMSelfNodeTitle {
            get {
                return ResourceManager.GetString("Str_NewKMSelfNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称未設定.
        /// </summary>
        internal static string Str_NewKMTextEntityTitle {
            get {
                return ResourceManager.GetString("Str_NewKMTextEntityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スケールバー.
        /// </summary>
        internal static string Str_ToolTip_DocVScaleBar {
            get {
                return ResourceManager.GetString("Str_ToolTip_DocVScaleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コントロールボタン＋クリックでリンク先を表示します.
        /// </summary>
        internal static string Str_ToolTip_ReportUrl {
            get {
                return ResourceManager.GetString("Str_ToolTip_ReportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字.
        /// </summary>
        internal static string Str_UiLbl_CharacterLiteral {
            get {
                return ResourceManager.GetString("Str_UiLbl_CharacterLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コメント：.
        /// </summary>
        internal static string Str_UiLbl_ReportReferencedSelfNodeTitle {
            get {
                return ResourceManager.GetString("Str_UiLbl_ReportReferencedSelfNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string Str_WarnDlgTitle {
            get {
                return ResourceManager.GetString("Str_WarnDlgTitle", resourceCulture);
            }
        }
    }
}
