//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjsBridge.ejsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ejsSessionToken", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
    [System.SerializableAttribute()]
    public partial class ejsSessionToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _creationTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _expireTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _isAuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid _sourceHostIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid _userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _creationTimeStamp {
            get {
                return this._creationTimeStampField;
            }
            set {
                if ((this._creationTimeStampField.Equals(value) != true)) {
                    this._creationTimeStampField = value;
                    this.RaisePropertyChanged("_creationTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _expireTimeStamp {
            get {
                return this._expireTimeStampField;
            }
            set {
                if ((this._expireTimeStampField.Equals(value) != true)) {
                    this._expireTimeStampField = value;
                    this.RaisePropertyChanged("_expireTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _firstName {
            get {
                return this._firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this._firstNameField, value) != true)) {
                    this._firstNameField = value;
                    this.RaisePropertyChanged("_firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _isAuthenticated {
            get {
                return this._isAuthenticatedField;
            }
            set {
                if ((this._isAuthenticatedField.Equals(value) != true)) {
                    this._isAuthenticatedField = value;
                    this.RaisePropertyChanged("_isAuthenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _lastName {
            get {
                return this._lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this._lastNameField, value) != true)) {
                    this._lastNameField = value;
                    this.RaisePropertyChanged("_lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _sourceHostId {
            get {
                return this._sourceHostIdField;
            }
            set {
                if ((this._sourceHostIdField.Equals(value) != true)) {
                    this._sourceHostIdField = value;
                    this.RaisePropertyChanged("_sourceHostId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _userId {
            get {
                return this._userIdField;
            }
            set {
                if ((this._userIdField.Equals(value) != true)) {
                    this._userIdField = value;
                    this.RaisePropertyChanged("_userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ejsAssignment", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService.AssignmentOp")]
    [System.SerializableAttribute()]
    public partial class ejsAssignment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssignmentContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommentCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DataSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EJSDatabaseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExternalAssignmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManagedByEJournalServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OriginalOwnerDbIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OwnerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ParentAssignmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudyCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EjsBridge.ejsService.ejsStudyMetaData[] studiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignmentContentType {
            get {
                return this.AssignmentContentTypeField;
            }
            set {
                if ((this.AssignmentContentTypeField.Equals(value) != true)) {
                    this.AssignmentContentTypeField = value;
                    this.RaisePropertyChanged("AssignmentContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentCount {
            get {
                return this.CommentCountField;
            }
            set {
                if ((this.CommentCountField.Equals(value) != true)) {
                    this.CommentCountField = value;
                    this.RaisePropertyChanged("CommentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DataSize {
            get {
                return this.DataSizeField;
            }
            set {
                if ((this.DataSizeField.Equals(value) != true)) {
                    this.DataSizeField = value;
                    this.RaisePropertyChanged("DataSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EJSDatabaseId {
            get {
                return this.EJSDatabaseIdField;
            }
            set {
                if ((this.EJSDatabaseIdField.Equals(value) != true)) {
                    this.EJSDatabaseIdField = value;
                    this.RaisePropertyChanged("EJSDatabaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExternalAssignmentId {
            get {
                return this.ExternalAssignmentIdField;
            }
            set {
                if ((this.ExternalAssignmentIdField.Equals(value) != true)) {
                    this.ExternalAssignmentIdField = value;
                    this.RaisePropertyChanged("ExternalAssignmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManagedByEJournalServer {
            get {
                return this.IsManagedByEJournalServerField;
            }
            set {
                if ((this.IsManagedByEJournalServerField.Equals(value) != true)) {
                    this.IsManagedByEJournalServerField = value;
                    this.RaisePropertyChanged("IsManagedByEJournalServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifiedDate {
            get {
                return this.LastModifiedDateField;
            }
            set {
                if ((this.LastModifiedDateField.Equals(value) != true)) {
                    this.LastModifiedDateField = value;
                    this.RaisePropertyChanged("LastModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginalOwnerDbId {
            get {
                return this.OriginalOwnerDbIdField;
            }
            set {
                if ((this.OriginalOwnerDbIdField.Equals(value) != true)) {
                    this.OriginalOwnerDbIdField = value;
                    this.RaisePropertyChanged("OriginalOwnerDbId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OwnerUserId {
            get {
                return this.OwnerUserIdField;
            }
            set {
                if ((this.OwnerUserIdField.Equals(value) != true)) {
                    this.OwnerUserIdField = value;
                    this.RaisePropertyChanged("OwnerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentAssignmentId {
            get {
                return this.ParentAssignmentIdField;
            }
            set {
                if ((this.ParentAssignmentIdField.Equals(value) != true)) {
                    this.ParentAssignmentIdField = value;
                    this.RaisePropertyChanged("ParentAssignmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudyCount {
            get {
                return this.StudyCountField;
            }
            set {
                if ((this.StudyCountField.Equals(value) != true)) {
                    this.StudyCountField = value;
                    this.RaisePropertyChanged("StudyCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EjsBridge.ejsService.ejsStudyMetaData[] studies {
            get {
                return this.studiesField;
            }
            set {
                if ((object.ReferenceEquals(this.studiesField, value) != true)) {
                    this.studiesField = value;
                    this.RaisePropertyChanged("studies");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ejsStudyMetaData", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService.AssignmentOp")]
    [System.SerializableAttribute()]
    public partial class ejsStudyMetaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommentCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentAssignmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentCount {
            get {
                return this.CommentCountField;
            }
            set {
                if ((this.CommentCountField.Equals(value) != true)) {
                    this.CommentCountField = value;
                    this.RaisePropertyChanged("CommentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifiedDate {
            get {
                return this.LastModifiedDateField;
            }
            set {
                if ((this.LastModifiedDateField.Equals(value) != true)) {
                    this.LastModifiedDateField = value;
                    this.RaisePropertyChanged("LastModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentAssignmentId {
            get {
                return this.ParentAssignmentIdField;
            }
            set {
                if ((this.ParentAssignmentIdField.Equals(value) != true)) {
                    this.ParentAssignmentIdField = value;
                    this.RaisePropertyChanged("ParentAssignmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ejsCourseDocument", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService.CourseOp")]
    [System.SerializableAttribute()]
    public partial class ejsCourseDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long _byteSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _courseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _creationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid _documentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _isAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _byteSize {
            get {
                return this._byteSizeField;
            }
            set {
                if ((this._byteSizeField.Equals(value) != true)) {
                    this._byteSizeField = value;
                    this.RaisePropertyChanged("_byteSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _courseId {
            get {
                return this._courseIdField;
            }
            set {
                if ((this._courseIdField.Equals(value) != true)) {
                    this._courseIdField = value;
                    this.RaisePropertyChanged("_courseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _creationDate {
            get {
                return this._creationDateField;
            }
            set {
                if ((this._creationDateField.Equals(value) != true)) {
                    this._creationDateField = value;
                    this.RaisePropertyChanged("_creationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _description {
            get {
                return this._descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this._descriptionField, value) != true)) {
                    this._descriptionField = value;
                    this.RaisePropertyChanged("_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid _documentId {
            get {
                return this._documentIdField;
            }
            set {
                if ((this._documentIdField.Equals(value) != true)) {
                    this._documentIdField = value;
                    this.RaisePropertyChanged("_documentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _isAvailable {
            get {
                return this._isAvailableField;
            }
            set {
                if ((this._isAvailableField.Equals(value) != true)) {
                    this._isAvailableField = value;
                    this.RaisePropertyChanged("_isAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ejsUserInfo", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService.UserOp")]
    [System.SerializableAttribute()]
    public partial class ejsUserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatabaseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAccountActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLoggedInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseName {
            get {
                return this.DatabaseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseNameField, value) != true)) {
                    this.DatabaseNameField = value;
                    this.RaisePropertyChanged("DatabaseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAccountActive {
            get {
                return this.IsAccountActiveField;
            }
            set {
                if ((this.IsAccountActiveField.Equals(value) != true)) {
                    this.IsAccountActiveField = value;
                    this.RaisePropertyChanged("IsAccountActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLoggedIn {
            get {
                return this.IsLoggedInField;
            }
            set {
                if ((this.IsLoggedInField.Equals(value) != true)) {
                    this.IsLoggedInField = value;
                    this.RaisePropertyChanged("IsLoggedIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ejsCourse", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService.CourseOp")]
    [System.SerializableAttribute()]
    public partial class ejsCourse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _creationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EjsBridge.ejsService.ejsCourseDocument[] _documentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _ownerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _creationDate {
            get {
                return this._creationDateField;
            }
            set {
                if ((this._creationDateField.Equals(value) != true)) {
                    this._creationDateField = value;
                    this.RaisePropertyChanged("_creationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _description {
            get {
                return this._descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this._descriptionField, value) != true)) {
                    this._descriptionField = value;
                    this.RaisePropertyChanged("_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EjsBridge.ejsService.ejsCourseDocument[] _documents {
            get {
                return this._documentsField;
            }
            set {
                if ((object.ReferenceEquals(this._documentsField, value) != true)) {
                    this._documentsField = value;
                    this.RaisePropertyChanged("_documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _isActive {
            get {
                return this._isActiveField;
            }
            set {
                if ((this._isActiveField.Equals(value) != true)) {
                    this._isActiveField = value;
                    this.RaisePropertyChanged("_isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _owner {
            get {
                return this._ownerField;
            }
            set {
                if ((object.ReferenceEquals(this._ownerField, value) != true)) {
                    this._ownerField = value;
                    this.RaisePropertyChanged("_owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
    [System.SerializableAttribute()]
    public partial class ejsFailureReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _failureCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _headerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _isHandledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception _originalExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _timeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _failureCode {
            get {
                return this._failureCodeField;
            }
            set {
                if ((this._failureCodeField.Equals(value) != true)) {
                    this._failureCodeField = value;
                    this.RaisePropertyChanged("_failureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _header {
            get {
                return this._headerField;
            }
            set {
                if ((object.ReferenceEquals(this._headerField, value) != true)) {
                    this._headerField = value;
                    this.RaisePropertyChanged("_header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _isHandled {
            get {
                return this._isHandledField;
            }
            set {
                if ((this._isHandledField.Equals(value) != true)) {
                    this._isHandledField = value;
                    this.RaisePropertyChanged("_isHandled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _message {
            get {
                return this._messageField;
            }
            set {
                if ((object.ReferenceEquals(this._messageField, value) != true)) {
                    this._messageField = value;
                    this.RaisePropertyChanged("_message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception _originalException {
            get {
                return this._originalExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this._originalExceptionField, value) != true)) {
                    this._originalExceptionField = value;
                    this.RaisePropertyChanged("_originalException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _timeStamp {
            get {
                return this._timeStampField;
            }
            set {
                if ((this._timeStampField.Equals(value) != true)) {
                    this._timeStampField = value;
                    this.RaisePropertyChanged("_timeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://meet.ejs/services", ConfigurationName="ejsService.EjsPublicService")]
    public interface EjsPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/Authenticate", ReplyAction="http://meet.ejs/services/EjsPublicService/AuthenticateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/AuthenticateejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        EjsBridge.ejsService.ejsSessionToken Authenticate(string UserName, string Password, System.Guid SourceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/UpdateUserPassword", ReplyAction="http://meet.ejs/services/EjsPublicService/UpdateUserPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/UpdateUserPasswordejsFailureReportFault" +
            "", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        void UpdateUserPassword(string UserName, string OldPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/InvalidateToken", ReplyAction="http://meet.ejs/services/EjsPublicService/InvalidateTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/InvalidateTokenejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        void InvalidateToken(EjsBridge.ejsService.ejsSessionToken Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/GetAllAssignments", ReplyAction="http://meet.ejs/services/EjsPublicService/GetAllAssignmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/GetAllAssignmentsejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        EjsBridge.ejsService.ejsAssignment[] GetAllAssignments(EjsBridge.ejsService.ejsSessionToken Token, bool IncludeNotAvailable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/SaveAndUploadAssignment", ReplyAction="http://meet.ejs/services/EjsPublicService/SaveAndUploadAssignmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/SaveAndUploadAssignmentejsFailureReport" +
            "Fault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        int SaveAndUploadAssignment(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsAssignment assignment, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/SaveStudyMetaData", ReplyAction="http://meet.ejs/services/EjsPublicService/SaveStudyMetaDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/SaveStudyMetaDataejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        void SaveStudyMetaData(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsStudyMetaData study, int parentAssignmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/GetAllCourseDocuments", ReplyAction="http://meet.ejs/services/EjsPublicService/GetAllCourseDocumentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/GetAllCourseDocumentsejsFailureReportFa" +
            "ult", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        EjsBridge.ejsService.ejsCourseDocument[] GetAllCourseDocuments(EjsBridge.ejsService.ejsSessionToken Token, bool IncludeNotAvailable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/GetAssignment", ReplyAction="http://meet.ejs/services/EjsPublicService/GetAssignmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/GetAssignmentejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        byte[] GetAssignment(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsAssignment assignment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/RegisterNewUser", ReplyAction="http://meet.ejs/services/EjsPublicService/RegisterNewUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/RegisterNewUserejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        void RegisterNewUser(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsUserInfo newUser, string userName, string password, int userGroupId, bool isAccountActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/GetAllRegisteredUsers", ReplyAction="http://meet.ejs/services/EjsPublicService/GetAllRegisteredUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/GetAllRegisteredUsersejsFailureReportFa" +
            "ult", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        EjsBridge.ejsService.ejsUserInfo[] GetAllRegisteredUsers(EjsBridge.ejsService.ejsSessionToken Token, int UserGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/GetRegisteredCoursesForUser", ReplyAction="http://meet.ejs/services/EjsPublicService/GetRegisteredCoursesForUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/GetRegisteredCoursesForUserejsFailureRe" +
            "portFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        EjsBridge.ejsService.ejsCourse[] GetRegisteredCoursesForUser(EjsBridge.ejsService.ejsSessionToken Token, bool includeCourseDocuments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/AddDocumentToCourse", ReplyAction="http://meet.ejs/services/EjsPublicService/AddDocumentToCourseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/AddDocumentToCourseejsFailureReportFaul" +
            "t", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        void AddDocumentToCourse(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsCourseDocument Document, int CourseId, byte[] DocumentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/GetCourseDocument", ReplyAction="http://meet.ejs/services/EjsPublicService/GetCourseDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/GetCourseDocumentejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        byte[] GetCourseDocument(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsCourseDocument Document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/GetAllRegisteredCourses", ReplyAction="http://meet.ejs/services/EjsPublicService/GetAllRegisteredCoursesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/GetAllRegisteredCoursesejsFailureReport" +
            "Fault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        EjsBridge.ejsService.ejsCourse[] GetAllRegisteredCourses(EjsBridge.ejsService.ejsSessionToken Token, bool includeDisabledCourses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/RegisterNewCourse", ReplyAction="http://meet.ejs/services/EjsPublicService/RegisterNewCourseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/RegisterNewCourseejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        void RegisterNewCourse(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsCourse NewCourse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/RegisterUserToCourse", ReplyAction="http://meet.ejs/services/EjsPublicService/RegisterUserToCourseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/RegisterUserToCourseejsFailureReportFau" +
            "lt", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        void RegisterUserToCourse(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsCourse Course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://meet.ejs/services/EjsPublicService/DeleteAssignment", ReplyAction="http://meet.ejs/services/EjsPublicService/DeleteAssignmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EjsBridge.ejsService.ejsFailureReport), Action="http://meet.ejs/services/EjsPublicService/DeleteAssignmentejsFailureReportFault", Name="ejsFailureReport", Namespace="http://schemas.datacontract.org/2004/07/EjsPublicService")]
        void DeleteAssignment(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsAssignment Assignment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface EjsPublicServiceChannel : EjsBridge.ejsService.EjsPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EjsPublicServiceClient : System.ServiceModel.ClientBase<EjsBridge.ejsService.EjsPublicService>, EjsBridge.ejsService.EjsPublicService {
        
        public EjsPublicServiceClient() {
        }
        
        public EjsPublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EjsPublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjsPublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjsPublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EjsBridge.ejsService.ejsSessionToken Authenticate(string UserName, string Password, System.Guid SourceId) {
            return base.Channel.Authenticate(UserName, Password, SourceId);
        }
        
        public void UpdateUserPassword(string UserName, string OldPassword, string NewPassword) {
            base.Channel.UpdateUserPassword(UserName, OldPassword, NewPassword);
        }
        
        public void InvalidateToken(EjsBridge.ejsService.ejsSessionToken Token) {
            base.Channel.InvalidateToken(Token);
        }
        
        public EjsBridge.ejsService.ejsAssignment[] GetAllAssignments(EjsBridge.ejsService.ejsSessionToken Token, bool IncludeNotAvailable) {
            return base.Channel.GetAllAssignments(Token, IncludeNotAvailable);
        }
        
        public int SaveAndUploadAssignment(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsAssignment assignment, byte[] data) {
            return base.Channel.SaveAndUploadAssignment(Token, assignment, data);
        }
        
        public void SaveStudyMetaData(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsStudyMetaData study, int parentAssignmentId) {
            base.Channel.SaveStudyMetaData(Token, study, parentAssignmentId);
        }
        
        public EjsBridge.ejsService.ejsCourseDocument[] GetAllCourseDocuments(EjsBridge.ejsService.ejsSessionToken Token, bool IncludeNotAvailable) {
            return base.Channel.GetAllCourseDocuments(Token, IncludeNotAvailable);
        }
        
        public byte[] GetAssignment(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsAssignment assignment) {
            return base.Channel.GetAssignment(Token, assignment);
        }
        
        public void RegisterNewUser(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsUserInfo newUser, string userName, string password, int userGroupId, bool isAccountActive) {
            base.Channel.RegisterNewUser(Token, newUser, userName, password, userGroupId, isAccountActive);
        }
        
        public EjsBridge.ejsService.ejsUserInfo[] GetAllRegisteredUsers(EjsBridge.ejsService.ejsSessionToken Token, int UserGroupId) {
            return base.Channel.GetAllRegisteredUsers(Token, UserGroupId);
        }
        
        public EjsBridge.ejsService.ejsCourse[] GetRegisteredCoursesForUser(EjsBridge.ejsService.ejsSessionToken Token, bool includeCourseDocuments) {
            return base.Channel.GetRegisteredCoursesForUser(Token, includeCourseDocuments);
        }
        
        public void AddDocumentToCourse(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsCourseDocument Document, int CourseId, byte[] DocumentData) {
            base.Channel.AddDocumentToCourse(Token, Document, CourseId, DocumentData);
        }
        
        public byte[] GetCourseDocument(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsCourseDocument Document) {
            return base.Channel.GetCourseDocument(Token, Document);
        }
        
        public EjsBridge.ejsService.ejsCourse[] GetAllRegisteredCourses(EjsBridge.ejsService.ejsSessionToken Token, bool includeDisabledCourses) {
            return base.Channel.GetAllRegisteredCourses(Token, includeDisabledCourses);
        }
        
        public void RegisterNewCourse(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsCourse NewCourse) {
            base.Channel.RegisterNewCourse(Token, NewCourse);
        }
        
        public void RegisterUserToCourse(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsCourse Course) {
            base.Channel.RegisterUserToCourse(Token, Course);
        }
        
        public void DeleteAssignment(EjsBridge.ejsService.ejsSessionToken Token, EjsBridge.ejsService.ejsAssignment Assignment) {
            base.Channel.DeleteAssignment(Token, Assignment);
        }
    }
}
