USE [master]
GO

/****** Object:  Database [meetMasterData]    Script Date: 03/10/2009 22:10:55 ******/
CREATE DATABASE [meetMasterData]
GO

ALTER DATABASE [meetMasterData] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [meetMasterData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [meetMasterData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [meetMasterData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [meetMasterData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [meetMasterData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [meetMasterData] SET ARITHABORT OFF 
GO

ALTER DATABASE [meetMasterData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [meetMasterData] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [meetMasterData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [meetMasterData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [meetMasterData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [meetMasterData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [meetMasterData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [meetMasterData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [meetMasterData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [meetMasterData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [meetMasterData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [meetMasterData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [meetMasterData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [meetMasterData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [meetMasterData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [meetMasterData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [meetMasterData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [meetMasterData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [meetMasterData] SET  READ_WRITE 
GO

ALTER DATABASE [meetMasterData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [meetMasterData] SET  MULTI_USER 
GO

ALTER DATABASE [meetMasterData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [meetMasterData] SET DB_CHAINING OFF 
GO

CREATE DATABASE [meetF_user_205]
GO

ALTER DATABASE [meetF_user_205] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [meetF_user_205].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

CREATE DATABASE [meetF_user_206]
GO

ALTER DATABASE [meetF_user_206] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [meetF_user_206].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
