//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejpClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ejpClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon ApplicationIconRound {
            get {
                object obj = ResourceManager.GetObject("ApplicationIconRound", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This assignment was created with an earlier version of EJournal Plus, therefor it cannot be opened in Comment Mode. If you wish do upgrade this Assignment, first open it in Normal Mode, then re-publish it to E Journal Server. After this you can open the new Published version in Comment Mode..
        /// </summary>
        internal static string ERR_AsgOpenFailed_Version {
            get {
                return ResourceManager.GetString("ERR_AsgOpenFailed_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 読み込もうとしたアサインメントは以前からこのアサインメントに含まれている。.
        /// </summary>
        internal static string ERR_AsgToMergeAlreadyExists {
            get {
                return ResourceManager.GetString("ERR_AsgToMergeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他人のアサインメントは削除出来ません。.
        /// </summary>
        internal static string ERR_CannotDelOthersAsg {
            get {
                return ResourceManager.GetString("ERR_CannotDelOthersAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ガイドを設定したいナレッジマップを選択して下さい。.
        /// </summary>
        internal static string ERR_ChooseKMToImportGuide {
            get {
                return ResourceManager.GetString("ERR_ChooseKMToImportGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 書き出したいレポートを選択して下さい。.
        /// </summary>
        internal static string ERR_ChooseReportToExport {
            get {
                return ResourceManager.GetString("ERR_ChooseReportToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷したいレポートを選択して下さい。.
        /// </summary>
        internal static string ERR_ChooseReportToPrint {
            get {
                return ResourceManager.GetString("ERR_ChooseReportToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開したいレポートを選択して下さい。.
        /// </summary>
        internal static string ERR_ChooseReportToPublish {
            get {
                return ResourceManager.GetString("ERR_ChooseReportToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E Journal Server address is invald. Make sure you include the http:// part of the Url..
        /// </summary>
        internal static string ERR_EjsUrlInvalid {
            get {
                return ResourceManager.GetString("ERR_EjsUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只今報告のサイトに接続出来ません。ネットワークの接続を確認して下さい。.
        /// </summary>
        internal static string ERR_ErrorReportNetworkFailed {
            get {
                return ResourceManager.GetString("ERR_ErrorReportNetworkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナレッジマップを書き出しする際に失敗しました。.
        /// </summary>
        internal static string ERR_ExportKMFailed {
            get {
                return ResourceManager.GetString("ERR_ExportKMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レポートを書き出しする際に失敗しました。.
        /// </summary>
        internal static string ERR_ExportReportFailed {
            get {
                return ResourceManager.GetString("ERR_ExportReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to まず最初にXPSドキュメントを追加したいスタディを選んでください。.
        /// </summary>
        internal static string ERR_MustChooseStudyToAddXps {
            get {
                return ResourceManager.GetString("ERR_MustChooseStudyToAddXps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開するためログインが必要です。.
        /// </summary>
        internal static string ERR_MustLogInBeforePublishAsg {
            get {
                return ResourceManager.GetString("ERR_MustLogInBeforePublishAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナレッジマップを追加するためファイルを保存しなければなりません。ファイルを保存して、ナレッジマップを追加しますか？.
        /// </summary>
        internal static string ERR_MustSaveBefireAddingKM {
            get {
                return ResourceManager.GetString("ERR_MustSaveBefireAddingKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 別のアサインメントをマージする前に，アサインメントを保存してください。.
        /// </summary>
        internal static string ERR_MustSaveBeforeMerge {
            get {
                return ResourceManager.GetString("ERR_MustSaveBeforeMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しく追加したスタディにガイドを読み込む前はアサインメントを一度保存して下さい。このガイドを削除しなければなりません。.
        /// </summary>
        internal static string ERR_MustSaveStudyBeforeAddingGuide {
            get {
                return ResourceManager.GetString("ERR_MustSaveStudyBeforeAddingGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開するアサインメントの名前を必ず入力して下さい。.
        /// </summary>
        internal static string ERR_NameNeededToPusblishAsg {
            get {
                return ResourceManager.GetString("ERR_NameNeededToPusblishAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erronous or No Live Space Url. You must specify the Url to your Live Space first. This is done under the main menu, Application Settings..
        /// </summary>
        internal static string ERR_NoLiveSpaceUriSet {
            get {
                return ResourceManager.GetString("ERR_NoLiveSpaceUriSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択してあるナレッジマップはまだガイド設定されていません。.
        /// </summary>
        internal static string ERR_SelectedKMHasNoGuide {
            get {
                return ResourceManager.GetString("ERR_SelectedKMHasNoGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Count does not contain a valid number..
        /// </summary>
        internal static string ERR_UndoCountInvalid {
            get {
                return ResourceManager.GetString("ERR_UndoCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失敗しました。.
        /// </summary>
        internal static string ERR_UnknownError {
            get {
                return ResourceManager.GetString("ERR_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows Live Spaces address is invald. Make sure you include the http:// part of the Url..
        /// </summary>
        internal static string ERR_WlsUrlInvalid {
            get {
                return ResourceManager.GetString("ERR_WlsUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナレッジマップは二枚より作成出来ません。.
        /// </summary>
        internal static string EX_AddKMFailed_Max {
            get {
                return ResourceManager.GetString("EX_AddKMFailed_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レポートは二枚より作成出来ません。.
        /// </summary>
        internal static string EX_AddReportFailed_Max {
            get {
                return ResourceManager.GetString("EX_AddReportFailed_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not Create new Assignment from the given document..
        /// </summary>
        internal static string EX_AsgCreateFromXPSFailed {
            get {
                return ResourceManager.GetString("EX_AsgCreateFromXPSFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されたアサインメントは削除できません。.
        /// </summary>
        internal static string EX_AsgDelFailed {
            get {
                return ResourceManager.GetString("EX_AsgDelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アサインメントを読み込もうとしたら失敗しました。.
        /// </summary>
        internal static string EX_AsgMergeFailed {
            get {
                return ResourceManager.GetString("EX_AsgMergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されたアサインメントが開けません。.
        /// </summary>
        internal static string EX_AsgOpenFailed {
            get {
                return ResourceManager.GetString("EX_AsgOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アサインメントを公開する際に失敗しました。.
        /// </summary>
        internal static string EX_AsgPublishFailed {
            get {
                return ResourceManager.GetString("EX_AsgPublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アサインメントを保存する際に失敗しました。.
        /// </summary>
        internal static string EX_AsgSaveFailed {
            get {
                return ResourceManager.GetString("EX_AsgSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このアサインメントのファイルに問題を発見したため、オートセーブが出来ません。改めて別の名前でファイルを保存して下さい。.
        /// </summary>
        internal static string EX_AutoSavedDisabled {
            get {
                return ResourceManager.GetString("EX_AutoSavedDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリケーションを閉じる際に失敗しました。.
        /// </summary>
        internal static string EX_CloseAppFailed {
            get {
                return ResourceManager.GetString("EX_CloseAppFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コースに登録出来ませんでした。しばらくしたら、もう一度試してみて下さい。.
        /// </summary>
        internal static string EX_CourseRegFailed {
            get {
                return ResourceManager.GetString("EX_CourseRegFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロードするためのフォルダを作成できません。作業を続けることができません。.
        /// </summary>
        internal static string EX_CreateAppDownloadFolderFailed {
            get {
                return ResourceManager.GetString("EX_CreateAppDownloadFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アプリケーションのデータを保存するフォルダを作成できません。このため，自動保存をすることはできません。.
        /// </summary>
        internal static string EX_CreateAppFoldersFailed {
            get {
                return ResourceManager.GetString("EX_CreateAppFoldersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一時保存のためのフォルダを作成できません。作業を続けることができません。.
        /// </summary>
        internal static string EX_CreateAppTempFolderFailed {
            get {
                return ResourceManager.GetString("EX_CreateAppTempFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ガイドの削除に失敗しました。.
        /// </summary>
        internal static string EX_DelGuideFailed {
            get {
                return ResourceManager.GetString("EX_DelGuideFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アサインメントを書き出しする際に失敗しました。.
        /// </summary>
        internal static string EX_ExportAsgFailed {
            get {
                return ResourceManager.GetString("EX_ExportAsgFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the comment count for the current working assignment..
        /// </summary>
        internal static string EX_GetCommentCountFailed {
            get {
                return ResourceManager.GetString("EX_GetCommentCountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像の読み込みに失敗しました。.
        /// </summary>
        internal static string EX_LoadImageFileFailed {
            get {
                return ResourceManager.GetString("EX_LoadImageFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定ファイルがありません。デフォルト設定で実行します。.
        /// </summary>
        internal static string EX_NoSettingsFile {
            get {
                return ResourceManager.GetString("EX_NoSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナレッジマップを印刷する際に失敗しました。.
        /// </summary>
        internal static string EX_PrintKMFailed {
            get {
                return ResourceManager.GetString("EX_PrintKMFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レポートを印刷する際に失敗しました。.
        /// </summary>
        internal static string EX_PrintReportFailed {
            get {
                return ResourceManager.GetString("EX_PrintReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原因が不明な問題が発生しました。eJournalPlusを閉じます。オートセーブされたファイルを確認して下さい。（マイドキュメント￥eJournalPlus￥AutoSave） メッセージは:.
        /// </summary>
        internal static string EX_UnhandledException {
            get {
                return ResourceManager.GetString("EX_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存に失敗した場合は、オートセーブを開いてみて下さい。.
        /// </summary>
        internal static string EX_UnhandledSaveFailed {
            get {
                return ResourceManager.GetString("EX_UnhandledSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Live Spacesと接続するための必要なファイルが見つかりませんでした。Windows Live Spacesに公開することが出来ません。eJournalPlusを再インストールして下さい。(Windows Live Spaces以外の機能には影響がありません。).
        /// </summary>
        internal static string EX_WlsDLLLoadFailed {
            get {
                return ResourceManager.GetString("EX_WlsDLLLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Current Working Assignment is not set..
        /// </summary>
        internal static string EX_WorkingAsgNotSet {
            get {
                return ResourceManager.GetString("EX_WorkingAsgNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されたアサインメントを削除しますか？.
        /// </summary>
        internal static string Q_DelAsg {
            get {
                return ResourceManager.GetString("Q_DelAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ガイドは削除しますか？.
        /// </summary>
        internal static string Q_DelGuide {
            get {
                return ResourceManager.GetString("Q_DelGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタッディを削除しますか？.
        /// </summary>
        internal static string Q_DelStudy {
            get {
                return ResourceManager.GetString("Q_DelStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択したファイルにはコメントがあるためコメントモードに開きます。宜しいですか？.
        /// </summary>
        internal static string Q_OpenAsComAsg {
            get {
                return ResourceManager.GetString("Q_OpenAsComAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力したパスは今の開いているファイルと一緒です。上書き保存は宜しいですか？.
        /// </summary>
        internal static string Q_OverwriteCurrentAsg {
            get {
                return ResourceManager.GetString("Q_OverwriteCurrentAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ガイドはすでに設定してあります。新しいガイドを設定するためこのガイドを削除しなければなりません。現在のガイドを削除して、新しいガイドを設定しますか？.
        /// </summary>
        internal static string Q_ReplaceCurrentKMGuide {
            get {
                return ResourceManager.GetString("Q_ReplaceCurrentKMGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集された項目を保存しますか？.
        /// </summary>
        internal static string Q_SaveChangesToAsg {
            get {
                return ResourceManager.GetString("Q_SaveChangesToAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コメントモードに切り替えます。宜しいですか？.
        /// </summary>
        internal static string Q_SwtichToCommentMode {
            get {
                return ResourceManager.GetString("Q_SwtichToCommentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通のモードに切り替えるとコメントは全てなくなります！宜しいですか？.
        /// </summary>
        internal static string Q_SwtichToNormalMode {
            get {
                return ResourceManager.GetString("Q_SwtichToNormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEET eJournalPlus 1.1.0.
        /// </summary>
        internal static string Str_AppVersionString {
            get {
                return ResourceManager.GetString("Str_AppVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Error.
        /// </summary>
        internal static string Str_AuthErrorTitle {
            get {
                return ResourceManager.GetString("Str_AuthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string Str_ConnFailedTitle {
            get {
                return ResourceManager.GetString("Str_ConnFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタディの追加.
        /// </summary>
        internal static string Str_DlgTitle_AddStudy {
            get {
                return ResourceManager.GetString("Str_DlgTitle_AddStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタディにドキュメントの追加.
        /// </summary>
        internal static string Str_DlgTitle_AddXps {
            get {
                return ResourceManager.GetString("Str_DlgTitle_AddXps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ejpファイルを選択.
        /// </summary>
        internal static string Str_DlgTitle_OpenAsg {
            get {
                return ResourceManager.GetString("Str_DlgTitle_OpenAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コメントモードで開くファイルを選択.
        /// </summary>
        internal static string Str_DlgTitle_OpenComAsg {
            get {
                return ResourceManager.GetString("Str_DlgTitle_OpenComAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPSドキュメントを選択.
        /// </summary>
        internal static string Str_DlgTitle_OpenXPS {
            get {
                return ResourceManager.GetString("Str_DlgTitle_OpenXPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        internal static string Str_DlgTitle_StartNew {
            get {
                return ResourceManager.GetString("Str_DlgTitle_StartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Str_ErrorTitle {
            get {
                return ResourceManager.GetString("Str_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナレッジマップ.
        /// </summary>
        internal static string Str_KnowledgeMapLiteral {
            get {
                return ResourceManager.GetString("Str_KnowledgeMapLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公開が無事終わりました。.
        /// </summary>
        internal static string Str_Msg_AsgPublished {
            get {
                return ResourceManager.GetString("Str_Msg_AsgPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - ファイル未作成.
        /// </summary>
        internal static string Str_NoAsgOpenedCreated {
            get {
                return ResourceManager.GetString("Str_NoAsgOpenedCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Assignment Set.
        /// </summary>
        internal static string Str_NoAsgSet {
            get {
                return ResourceManager.GetString("Str_NoAsgSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        internal static string Str_NoNameAssignmentTitle {
            get {
                return ResourceManager.GetString("Str_NoNameAssignmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを更新しました。再ログインが必要となります。.
        /// </summary>
        internal static string Str_PasswdUpdated {
            get {
                return ResourceManager.GetString("Str_PasswdUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 処理完了.
        /// </summary>
        internal static string Str_ProcessingEndedTitle {
            get {
                return ResourceManager.GetString("Str_ProcessingEndedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レポート.
        /// </summary>
        internal static string Str_ReportLiteral {
            get {
                return ResourceManager.GetString("Str_ReportLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいナレッジマップ.
        /// </summary>
        internal static string Str_ToolTip_NewKMTab {
            get {
                return ResourceManager.GetString("Str_ToolTip_NewKMTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいレポート.
        /// </summary>
        internal static string Str_ToolTip_NewReportTab {
            get {
                return ResourceManager.GetString("Str_ToolTip_NewReportTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開く.
        /// </summary>
        internal static string Str_UI_BtnOpen {
            get {
                return ResourceManager.GetString("Str_UI_BtnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 読み込む.
        /// </summary>
        internal static string Str_UI_BtnOpenAsgForMerge {
            get {
                return ResourceManager.GetString("Str_UI_BtnOpenAsgForMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Comments: .
        /// </summary>
        internal static string Str_Ui_LblComments {
            get {
                return ResourceManager.GetString("Str_Ui_LblComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黒.
        /// </summary>
        internal static string Str_UiLbl_Black {
            get {
                return ResourceManager.GetString("Str_UiLbl_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青.
        /// </summary>
        internal static string Str_UiLbl_Blue {
            get {
                return ResourceManager.GetString("Str_UiLbl_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル.
        /// </summary>
        internal static string Str_UiLbl_FileLiteral {
            get {
                return ResourceManager.GetString("Str_UiLbl_FileLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドキュメントを選択して下さい。。。.
        /// </summary>
        internal static string Str_UiLbl_FirstXPSLocation {
            get {
                return ResourceManager.GetString("Str_UiLbl_FirstXPSLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドキュメントを選択して下さい。。。.
        /// </summary>
        internal static string Str_UiLbl_FirstXPSName {
            get {
                return ResourceManager.GetString("Str_UiLbl_FirstXPSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緑.
        /// </summary>
        internal static string Str_UiLbl_Green {
            get {
                return ResourceManager.GetString("Str_UiLbl_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤.
        /// </summary>
        internal static string Str_UiLbl_Red {
            get {
                return ResourceManager.GetString("Str_UiLbl_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黄.
        /// </summary>
        internal static string Str_UiLbl_Yellow {
            get {
                return ResourceManager.GetString("Str_UiLbl_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アサインメントをダウンロード中。.
        /// </summary>
        internal static string Str_UiLblDownloadingAsg {
            get {
                return ResourceManager.GetString("Str_UiLblDownloadingAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string Str_UiLblIdle {
            get {
                return ResourceManager.GetString("Str_UiLblIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        internal static string Str_UiLblNone {
            get {
                return ResourceManager.GetString("Str_UiLblNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失敗しました。.
        /// </summary>
        internal static string Str_UndefinedError {
            get {
                return ResourceManager.GetString("Str_UndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Error.
        /// </summary>
        internal static string Str_VersionErrorTitle {
            get {
                return ResourceManager.GetString("Str_VersionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Str_WarnTitle {
            get {
                return ResourceManager.GetString("Str_WarnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJournalPlus - レポート.
        /// </summary>
        internal static string Str_WlsPostTitle {
            get {
                return ResourceManager.GetString("Str_WlsPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意：まだ1度も保存されていません.
        /// </summary>
        internal static string Str_Wrn_UnsavedAsg {
            get {
                return ResourceManager.GetString("Str_Wrn_UnsavedAsg", resourceCulture);
            }
        }
    }
}
